# Gitleaks configuration file
title = "DevSecOps Demo Gitleaks Configuration"

# Rules for detecting secrets
[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws_secret_access_key\s*=\s*[A-Za-z0-9/+=]{40}'''

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN (RSA|OPENSSH|DSA|EC|PGP) PRIVATE KEY-----'''

[[rules]]
id = "api-key"
description = "Generic API Key"
regex = '''(?i)(api_key|apikey|api-key)\s*[:=]\s*['"][a-zA-Z0-9_\-]{20,}['"]'''

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'''

# Allowlist paths and patterns
[allowlist]
paths = [
  ".gitleaks.toml",
  ".gitleaksignore",
  "README.md",
  "package-lock.json",
  "package.json",
  "node_modules/**",
  "src/index.js",
  "*.md",
  "demo-*.sh"
]

# Allow specific patterns for demo purposes (uncomment if needed)
# regexes = [
#   '''sk-1234567890abcdef''',
#   '''admin123''',
#   '''AKIAIOSFODNN7EXAMPLE'''
# ]